
export const ZOOM_OUT_SCALE = 0.55;
export const ANIMATION_DURATION = {
  ZOOM_OUT: 250,
  SCROLL: 500,
  ZOOM_IN: 250,
  SCROLL_FILL: 350,
};
export const INACTIVITY_TIMEOUT = 2000;
export const UI_LAYOUT = {
  CURRENT_SECTION_TOP: 32,
  SIDEBAR_TOP: 80,
  SIDEBAR_RIGHT: 48,
  SCROLLBAR_RIGHT: 32,
  SCROLLBAR_WIDTH: 8,
  TOTAL_VERTICAL_PADDING: 140,
};
export const MOBILE_ZOOM_OUT_SCALE = 0.40;
